-- DDL básico para ServicioAdministracion
DROP TABLE IF EXISTS CAMIONES;
DROP TABLE IF EXISTS DEPOSITOS;
DROP TABLE IF EXISTS TARIFAS;
DROP SEQUENCE IF EXISTS SEQ_CAMION_ID;
DROP SEQUENCE IF EXISTS SEQ_DEPOSITO_ID;
DROP SEQUENCE IF EXISTS SEQ_TARIFA_ID;

CREATE SEQUENCE IF NOT EXISTS SEQ_CAMION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_DEPOSITO_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_TARIFA_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE TARIFAS (
  ID_TARIFA INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_TARIFA_ID,
  NOMBRE VARCHAR(200) NOT NULL,
  DESCRIPCION VARCHAR(2048),
  VALOR_BASE DECIMAL(10,2),
  TIPO_CALCULO VARCHAR(50),
  CONSTRAINT PK_TARIFA PRIMARY KEY (ID_TARIFA)
);

CREATE TABLE DEPOSITOS (
  ID_DEPOSITO INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_DEPOSITO_ID,
  NOMBRE VARCHAR(200) NOT NULL,
  DIRECCION VARCHAR(400),
  LATITUD DECIMAL(9,6),
  LONGITUD DECIMAL(9,6),
  COSTO_DIARIO DECIMAL(10,2),
  CAPACIDAD_MAX INTEGER,
  CONSTRAINT PK_DEPOSITO PRIMARY KEY (ID_DEPOSITO)
);

CREATE TABLE CAMIONES (
  ID_CAMION INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_CAMION_ID,
  DOMINIO VARCHAR(30) UNIQUE NOT NULL,
  MARCA VARCHAR(100),
  MODELO VARCHAR(100),
  CAPACIDAD_PESO DECIMAL(12,2),
  CAPACIDAD_VOLUMEN DECIMAL(12,2),
  CONSUMO_KM DECIMAL(10,2),
  COSTO_KM_BASE DECIMAL(10,2),
  ESTADO VARCHAR(50),
  TRANSPORTISTA VARCHAR(200),
  ID_TARIFA INTEGER,
  CONSTRAINT PK_CAMION PRIMARY KEY (ID_CAMION),
  CONSTRAINT FK_CAMION_TARIFA FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);
